### ISSUE TITLE
Publish Code

### ISSUE THREAD

**Issue by kiesman99** [sigmaxipi/chromium-for-stadia#1]
Hey There :)

Is there a possibility you publish the full code, so I could investigate the modded files?
I just tried playing stadia on chrome using your manual guide from the reddit post. Unfortunately the chromium apk you published does crash on daydream and i want to figure out why :)

Thank you! Nice work btw :)

**Comment by sigmaxipi** [comment]
Trying to create a real repo isn't feasible due to the size of the Chromium codebase. But all of my changes are at https://github.com/sigmaxipi/chromium-for-stadia/blob/master/chromiumForStadia.diff so you can just patch that into a Chromium checkout and generate my apk.
