### ISSUE TITLE
Enter in desktop mode by default

### ISSUE THREAD

**Issue by leolimajr** [sigmaxipi/chromium-for-stadia#18]
On Android TV (Shield or Mi Box) it would be great to enable desktop by default every time you open chromium. Is it possible?
Thanks!

**Comment by sigmaxipi** [comment]
The original version did this, but that caused https://github.com/sigmaxipi/chromium-for-stadia/issues/4 for some people so I had to undo that change.

**Comment by leolimajr** [comment]
I see! Otherwise you won't be able to login. That makes sense.  I'd say this is closed then.
