### ISSUE TITLE
Issues using on the SG Note 9 Exynos variant.

### ISSUE THREAD

**Issue by Hadesthepyro** [sigmaxipi/chromium-for-stadia#2]
Games refuse to actually go ahead and load on my SG Note 9 Exynos variant phone.

**Comment by sigmaxipi** [comment]
What is the error or behavior that you're seeing?

**Comment by Hadesthepyro** [comment]
Game takes a long time to load then site reloads.

**Comment by sigmaxipi** [comment]
Is this the same behavior as https://github.com/sigmaxipi/chromium-for-stadia/issues/3 ?

**Comment by Hadesthepyro** [comment]
Yes actually. However now I'm running into a issue where the audio will appear a whole second behind the display.

**Comment by sigmaxipi** [comment]
The audio lag is a general bug with Stadia: https://www.reddit.com/r/Stadia/search?q=audio+lag&restrict_sr=on&include_over_18=on

**Comment by sigmaxipi** [comment]
Duplicate of #3

**Comment by Hadesthepyro** [comment]
Er... I'm getting the audio before the image not after like the Reddit posts are...

**Comment by sigmaxipi** [comment]
I think that's the same issue. It inconsistently happens to some people and not others.
