### ISSUE TITLE
Oculus quest 2 stutter the whole time

### ISSUE THREAD

**Issue by awwe** [sigmaxipi/chromium-for-stadia#29]
Wifi 5ghz. 100mbps down  

Alla 60fps games like sundered, panzer dragoon has stutter the whole time making them more or less not playable 😐

**Comment by sigmaxipi** [comment]
Stadia runs at 60Hz. You'll need to run `adb shell setprop debug.oculus.refreshRate 60` to force your headset into 60Hz mode for best performance. You can see the current FPS by running adb logcat *:S VrApi:*
