### ISSUE TITLE
Game doesn't load

### ISSUE THREAD

**Issue by Cheomm88** [sigmaxipi/chromium-for-stadia#3]
I tried the modified apk during this morning and game loaded, i was able to play using 4G... This afternoon games doesnt load with 4G nor wifi.

Using s10+

**Comment by sigmaxipi** [comment]
What is the error or behavior that you're seeing?

**Comment by Cheomm88** [comment]
I enter in website and press play in a game, it loads the Boot screen and
takes a long time with the loading circle on the left botton.

Until it appears the error "Open the game again" "Open the game again to
play"

**Comment by sigmaxipi** [comment]
Someone else reported a similar issue: https://www.reddit.com/r/Stadia/comments/e11897/how_to_get_stadia_running_in_android_chrome_on/f8ryxyr/

They were getting an Italian error message. Were you getting a Spanish one? Can you try changing your language settings to English and trying again? This may also be a regional issue.

**Comment by sigmaxipi** [comment]
I ran into this on one of my devices which was working perfectly this morning. If you're familiar with Chrome dev tools for Android, you can run `window.localStorage.clear()`. Or go to stadia.google.com and then type `javascript:window.localStorage.clear()` into the URL bar. That fixed it for me because the wrong `video_codec_implementation_by_codec_key` was set in the browser.

**Comment by Cheomm88** [comment]
Hello,
I went to Options, Privacy and delete all data from websites (cookies) now
it works!! Thanks!

**Comment by Cheomm88** [comment]
Hi there,
My buddy pass had the same issur and fixed it with the privacy setting on
chromium removing all the cookies

**Comment by sigmaxipi** [comment]
Deleting all the data from websites should also clear local storage. I'm glad you got it working.

**Comment by Cheomm88** [comment]
I checked that with private mode I am able to play games, looks something realated with local data

**Comment by sigmaxipi** [comment]
I updated the apk to work around this issue.
