### ISSUE TITLE
Couldn't sign in to Google

### ISSUE THREAD

**Issue by BAnd313** [sigmaxipi/chromium-for-stadia#30]
When I try to sign in to Google it says that the browser is unsafe. Tested on a Fire TV stick 4k and my Pixel 3a.

![screenshot](https://user-images.githubusercontent.com/28732212/101012637-6952ca80-3563-11eb-9ed8-df131c064ec9.png)

I guess the chromium release is too old now. Is there any way to log in here? Is it necessary to rebuild a newer version of chromium?

**Comment by cappee** [comment]
I have your same issue, how have you resolved?

**Comment by BAnd313** [comment]
Duplicate of #4 

In short: go to google.com with desktop mode disabled and sign in, then enable desktop mode and go to stadia
