### ISSUE TITLE
How do you login?

### ISSUE THREAD

**Issue by dragonfax** [sigmaxipi/chromium-for-stadia#4]
This copy of chromium on my android phone ( a moto z3) wont' let me log into my account on stadia.com. It either says I'm trying to log into my account on a browser that doesn't let them keep my account secure, or it says my account already exists on the phone.

**Comment by sigmaxipi** [comment]
Don't try to use the Chromium app's account sync. Instead, just go to stadia.google.com or any other Google site and log in with your Stadia account. I'm not sure why the Chrome app sync doesn't work on this custom build, but I ran into the same issue.

**Comment by mgsjoker** [comment]
I tried with sync on and off and get the same results no matter what I do am using a samsung galaxy fold on the latest firmware and I tried on both versions  of the apk is there any other things I can try to get round this it let me sign into my hotmail account that's linked to my google but I cant play stadia with it

**Comment by sigmaxipi** [comment]
@dragonfax @mgsjoker what countries are you in? Others are reporting this issue but most people don't seem to have this problem and I haven't been able to reproduce it on my devices.

Can you try a stock Chromium for Android build from https://www.chromium.org/getting-involved/download-chromium (go to the https://download-chromium.appspot.com link there from your Android phone) and tell me if that version of Chromium lets you log in?

Searching for that error message makes me think that Google's anti-malware system doesn't like the spoofed user agent in my apk: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

**Comment by dragonfax** [comment]
USA, Los Angeles.

Thats got to be it. Because I tried the stock Chromium and was able to log into stadia fine. Though I was not able to use the controller, but I suppose thats expected.

Note I have been able to play Stadia on my phone, using the controller in regular Chrome. By using that javascript: url bar patch that people have been passing around. Its works fine for me. So I don't need this solution anymore. But perhaps others do.

**Comment by mgsjoker** [comment]
Downloaded the link you provided  it and installed it signed in first time no issues

**Comment by mgsjoker** [comment]
Also I am in Scotland uk

**Comment by mkiisoft** [comment]
I'm having the same issue: San Francisco - USA, I'm not being able to login having the exact same response.

**Comment by erikpi** [comment]
Same issue - Stockholm, Sweden.

Cant add account with sync because "Account already used on this device", and cant sign in as per first post in this issue.

**Comment by sigmaxipi** [comment]
Can you try uninstall & reinstalling the apk? And then take a screenshot of the failure message? I'm still unable to reproduce this issue. Also, does incognito mode work? And does manually setting Desktop mode before trying to sign in help?

**Comment by dragonfax** [comment]
I did try reinstalling. Also, incognito does not work.

**Comment by taylorschaerer** [comment]
From what I've heard Stadia won't run on the Oculus Go, but at the very least I should be able to sign in. However, I am getting the same error as the others have reported. The message pops up right after you enter your gmail password. Tried uninstalling and reinstalling the apk but made no difference. Interesting to note however, that when I then tried to log in to my gmail on the stock Oculus browser I got the same message there too. Unfortunately I can't recall if I've ever tried logging into my google account on my Oculus Go before, so I'm uncertain if this is a new problem or if it's been this way for a while.

Can try to pull a screenshot for you later tonight if no one else has provided one yet.

**Comment by taylorschaerer** [comment]
Perhaps useful:
When the error pops up there is a link to more info about the error. This is that link:

https://support.google.com/accounts/answer/7675428

**Comment by sigmaxipi** [comment]
Can you try the latest version that I uploaded?

**Comment by taylorschaerer** [comment]
I solved the error on the stock Oculus browser by going to 'settings' -> 'login to Facebook' (this is in the browser itself, not the OS) and clicking on my Facebook account. No longer got the issue signing into google after that. Unfortunately this did nothing to help the situation in the modified chromium browser.

**Comment by taylorschaerer** [comment]
Oops just saw your comment. Give me a sec.

**Comment by taylorschaerer** [comment]
Latest version works! Was able to sign in! Am getting redirected to stadia.google.com/warning/7 now but I assume that's because it doesn't like the Go hardware and is nothing to do with the apk. Awesome work! Thanks! :)

**Comment by sigmaxipi** [comment]
You'll need to manually enable Desktop mode in my apk to avoid that `warning/7` redirect. I removed the user-agent hack that spoofed desktop mode because that was causing this login issue. I'm guessing Google didn't like this fake UA.

**Comment by mgsjoker** [comment]
This is what am getting message wise and that's with me enabling desktop mode myself 
![Screenshot_20191204-210242_Chromium](https://user-images.githubusercontent.com/58445476/70181351-a3338b80-16d9-11ea-9d2d-1fbee53a2742.jpg)

**Comment by dragonfax** [comment]
![Screenshot_20191204-131053](https://user-images.githubusercontent.com/933806/70181886-9beb8e00-1697-11ea-892e-27cf88e9e981.png)
No good for me, sorry. Later version

**Comment by sigmaxipi** [comment]
Can you try the apk at https://github.com/sigmaxipi/chromium-for-stadia/releases/download/1/ChromiumForStadiaNoPatch.apk and see if it has login issues?

**Comment by sigmaxipi** [comment]
Also, uninstalling the apk and trying to log in to stadia.google.com may help.

**Comment by mgsjoker** [comment]
Downloaded it and got the same issue mate I am already signed in on stadia.google i signed out tried and signed back in and tried again same out come

**Comment by erikpi** [comment]
Confirming latest build works to login and reach the stadia game page, will try later with the controller, i'll give an update

**Comment by anchapin** [comment]
I'm having this problem also. I tried both versions of the APK and even tried logging in with incognito mode and that didn't work. I'm in Virginia in US and have 2 factor authentication on my Google account. Not sure if that matters.

**Comment by Scraft** [comment]
I had this issue, I disabled desktop mode, went through the auth, then enabled desktop mode again and it resolved the issue.
