### ISSUE TITLE
Xbox controller problems 

### ISSUE THREAD

**Issue by rawpie2** [sigmaxipi/chromium-for-stadia#6]
When I use my xbox controller it works perfectly until I try to aim or shoot, when I do that my head flies up and pressing rt moves the up and down of my head and I cant use the stick to move my head anymore.

**Comment by sigmaxipi** [comment]
Can you try that controller on https://html5gamepad.com/ and check if it works properly? Also, what device & OS are you using? And what is the "Controller Name" on that page?. And does **Android Settings -> Bluetooth -> Connected devices -> Xbox controller -> Settings** show the gamepad as an "Input device"?

**Comment by rawpie2** [comment]
Device: Galaxy s9+
The controller is wired via OTG not bluetooth
Its listed as Microsoft X-Box One Elite pad
When I hit RT axis 3 jumps to 1 and than shoots to -1, staying there, completely locking control of axis 3.

**Comment by sigmaxipi** [comment]
Can you try the latest apk and see if you still have the issue? If so, test the gamepad with the official Chrome app and https://html5gamepad.com/. If you still have a problem, file a new issue with the Chrome team at https://bugs.chromium.org/p/chromium/issues/list
