### ISSUE TITLE
[RFE] Improve the user experience

### ISSUE THREAD

**Issue by e-minguez** [sigmaxipi/chromium-for-stadia#8]
It would be nice to have:

* Chromium to open by default in 'desktop mode'
* Customize the Chromium icon and name as 'Stadia' or something similar
* Launch Chromium in full screen, home page set to stadia.com with no tabs and with rotation locked to landscape

I'm not sure if those options are customizable but it would be nice :)

Thanks for your work!!!

**Comment by sigmaxipi** [comment]
>Chromium to open by default in 'desktop mode'
This resulted in an issue with logins so I stopped doing that: https://github.com/sigmaxipi/chromium-for-stadia/issues/4

>Customize the Chromium icon and name as 'Stadia' or something similar
I considered this, but there are copyright and trademark issues with using 'Stadia' in any unofficial app so I decided against it. You may be able to use the [older version of the apk](https://github.com/sigmaxipi/chromium-for-stadia/blob/9221d4728f07f7cf0f4d4ae69c00e941d7ef7162/ChromiumForStadia.apk) that did this. If you log in with the newer apk and then `adb install -r -d` the older apk, it may work.

>Launch Chromium in full screen, home page set to stadia.com with no tabs and with rotation locked to landscape
This is hard. I looked into this but I don't have enough Chromium experience so I decided it wasn't worth it. You can add a webpage to the home screen in Chromium's menu, but when I tried it just now, it didn't load the desktop site. However, you may be able to do this using the older apk above.
