### ISSUE TITLE
Hide button bar? 

### ISSUE THREAD

**Issue by Scraft** [sigmaxipi/chromium-for-stadia#9]
![Screenshot_20191225_225708_org chromium chrome](https://user-images.githubusercontent.com/294599/71451295-6b64b480-276a-11ea-9905-33779bf0f3df.jpg)

I have the same issue on normal Chrome or this build, it doesn't go into "full" fullscreen and instead leaves the bar/home/multitask buttons and bar visible. Is there a fix for this? I have a P20 Pro phone.

**Comment by vrodriguezf** [comment]
Same here on a Mi A2

**Comment by khalid-salad** [comment]
![Screenshot_20200110-071248026](https://user-images.githubusercontent.com/1640592/72155557-fd7ad880-3378-11ea-81b4-1aeb3c2b0ed3.png)

Same for me on Asus ROG Phone II.

**Comment by sigmaxipi** [comment]
This is due to https://bugs.chromium.org/p/chromium/issues/detail?id=933436#c7

**Comment by sigmaxipi** [comment]
Fixed in 4/19 build
